FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

# Copy go.mod
COPY go.mod ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Run air
CMD ["air", "-c", ".air.toml"]
