package recipe

import (
	"encoding/json"
	"strconv"
)

// Recipe represents a structured recipe generated by AI
type Recipe struct {
	RecipeName          string        `json:"recipe_name"`
	Description         string        `json:"description,omitempty"`
	PrepTime            *int          `json:"prep_time,omitempty"`
	CookingTime         *int          `json:"cooking_time,omitempty"`
	TotalTime           *int          `json:"total_time,omitempty"`
	OriginalServings    *int          `json:"original_serving_size,omitempty"`
	DifficultyRating    *int          `json:"difficulty_rating,omitempty"`
	FocusedDiet         string        `json:"focused_diet,omitempty"`
	EstimatedCalories   *int          `json:"estimated_calories,omitempty"`
	Ingredients         []Ingredient  `json:"ingredients"`
	Instructions        []Instruction `json:"instructions"`
	Parts               []RecipePart  `json:"parts,omitempty"`
	Nutrition           Nutrition     `json:"nutrition"`
	CuisineCategories   []string      `json:"cuisine_categories,omitempty"`
	MealTypes           []string      `json:"meal_types,omitempty"`
	Occasions           []string      `json:"occasions,omitempty"`
	DietaryRestrictions []string      `json:"dietary_restrictions,omitempty"`
	Equipment           []string      `json:"equipment,omitempty"`
	Language            string        `json:"language"`
}

// RecipePart represents a section of a recipe with its own ingredients and instructions
type RecipePart struct {
	ID           string        `json:"id,omitempty"`
	Name         string        `json:"name"`
	Description  string        `json:"description,omitempty"`
	DisplayOrder int           `json:"display_order"`
	IsOptional   bool          `json:"is_optional"`
	PrepTime     *int          `json:"prep_time,omitempty"`
	CookingTime  *int          `json:"cooking_time,omitempty"`
	Ingredients  []Ingredient  `json:"ingredients"`
	Instructions []Instruction `json:"instructions"`
}

// StringOrNumber can unmarshal from JSON string or number
type StringOrNumber string

func (s *StringOrNumber) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*s = ""
		return nil
	}
	// Try unmarshal as string first
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		*s = StringOrNumber(str)
		return nil
	}
	// Try as number
	var num float64
	if err := json.Unmarshal(data, &num); err != nil {
		return err
	}
	*s = StringOrNumber(strconv.FormatFloat(num, 'f', -1, 64))
	return nil
}

// Ingredient represents a recipe ingredient
type Ingredient struct {
	ID               string         `json:"id,omitempty"` // NEW: Real database ID
	PartID           *string        `json:"part_id,omitempty"`
	OriginalQuantity StringOrNumber `json:"original_quantity"`
	OriginalUnit     string         `json:"original_unit"`
	TotalQuantity    StringOrNumber `json:"total_quantity"`
	Quantity         StringOrNumber `json:"quantity"`
	Unit             string         `json:"unit"`
	Name             string         `json:"name"`
}

// StepIngredient represents an ingredient used in a specific step
type StepIngredient struct {
	IngredientName string `json:"ingredient_name"`
	QuantityUsed   string `json:"quantity_used"`
}

// Instruction represents a recipe instruction step
type Instruction struct {
	StepNumber             int              `json:"step_number"`
	PartID                 *string          `json:"part_id,omitempty"`
	Instruction            string           `json:"instruction"`
	TimerData              []Timer          `json:"timer_data,omitempty"`
	InstructionRich        string           `json:"instruction_rich,omitempty"`
	InstructionRichVersion int              `json:"instruction_rich_version,omitempty"`
	IngredientsUsed        []StepIngredient `json:"ingredients_used,omitempty"`
}

// Timer represents a cooking timer extracted from instruction text
type Timer struct {
	DurationSeconds int    `json:"duration_seconds"`
	DurationText    string `json:"duration_text"`
	Label           string `json:"label"`
	Type            string `json:"type"`
	Category        string `json:"category"`
}

// Nutrition represents nutritional information
type Nutrition struct {
	Protein float64 `json:"protein"`
	Carbs   float64 `json:"carbs"`
	Fat     float64 `json:"fat"`
	Fiber   float64 `json:"fiber"`
}

// HasParts returns true if the recipe has parts
func (r *Recipe) HasParts() bool {
	return len(r.Parts) > 0
}

// FlattenIngredients returns all ingredients from all parts combined
func (r *Recipe) FlattenIngredients() []Ingredient {
	if !r.HasParts() {
		return r.Ingredients
	}

	var result []Ingredient
	for _, part := range r.Parts {
		result = append(result, part.Ingredients...)
	}
	return result
}

// FlattenInstructions returns all instructions from all parts combined
func (r *Recipe) FlattenInstructions() []Instruction {
	if !r.HasParts() {
		return r.Instructions
	}

	var result []Instruction
	for _, part := range r.Parts {
		result = append(result, part.Instructions...)
	}
	return result
}

// recipeResponseInner is the internal response structure for recipe data
type recipeResponseInner struct {
	RecipeName        string `json:"recipe_name"`
	Description       string `json:"description"`
	PrepTime          *int   `json:"prep_time"`
	CookingTime       *int   `json:"cooking_time"`
	TotalTime         *int   `json:"total_time"`
	OriginalServings  *int   `json:"original_serving_size"`
	DifficultyRating  *int   `json:"difficulty_rating"`
	FocusedDiet       string `json:"focused_diet"`
	EstimatedCalories *int   `json:"estimated_calories"`
}

// recipeResponseOuter is the outer response structure from AI
type recipeResponseOuter struct {
	Recipe              recipeResponseInner `json:"recipe"`
	Ingredients         []Ingredient        `json:"ingredients"`
	Instructions        []Instruction       `json:"instructions"`
	Parts               []RecipePart        `json:"parts,omitempty"`
	Nutrition           Nutrition           `json:"nutrition"`
	CuisineCategories   []string            `json:"cuisine_categories"`
	MealTypes           []string            `json:"meal_types"`
	Occasions           []string            `json:"occasions"`
	DietaryRestrictions []string            `json:"dietary_restrictions"`
	Equipment           []string            `json:"equipment"`
	Language            string              `json:"language"`
}
