package recipe

import (
	"encoding/json"
	"strconv"
)

// Recipe represents a structured recipe generated by AI
type Recipe struct {
	RecipeName          string
	Description         string
	PrepTime            *int
	CookingTime         *int
	TotalTime           *int
	OriginalServings    *int
	DifficultyRating    *int
	FocusedDiet         string
	EstimatedCalories   *int
	Ingredients         []Ingredient
	Instructions        []Instruction
	Nutrition           Nutrition
	CuisineCategories   []string
	MealTypes           []string
	Occasions           []string
	DietaryRestrictions []string
	Equipment           []string
}

// StringOrNumber can unmarshal from JSON string or number
type StringOrNumber string

func (s *StringOrNumber) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*s = ""
		return nil
	}
	// Try unmarshal as string first
	var str string
	if err := json.Unmarshal(data, &str); err == nil {
		*s = StringOrNumber(str)
		return nil
	}
	// Try as number
	var num float64
	if err := json.Unmarshal(data, &num); err != nil {
		return err
	}
	*s = StringOrNumber(strconv.FormatFloat(num, 'f', -1, 64))
	return nil
}

// Ingredient represents a recipe ingredient
type Ingredient struct {
	OriginalQuantity StringOrNumber `json:"original_quantity"`
	OriginalUnit     string         `json:"original_unit"`
	Quantity         float64        `json:"quantity"`
	Unit             string         `json:"unit"`
	Name             string         `json:"name"`
}

// Instruction represents a recipe instruction step
type Instruction struct {
	StepNumber  int    `json:"step_number"`
	Instruction string `json:"instruction"`
}

// Nutrition represents nutritional information
type Nutrition struct {
	Protein float64 `json:"protein"`
	Carbs   float64 `json:"carbs"`
	Fat     float64 `json:"fat"`
	Fiber   float64 `json:"fiber"`
}

// recipeResponseInner is the internal response structure for recipe data
type recipeResponseInner struct {
	RecipeName        string `json:"recipe_name"`
	Description       string `json:"description"`
	PrepTime          *int   `json:"prep_time"`
	CookingTime       *int   `json:"cooking_time"`
	TotalTime         *int   `json:"total_time"`
	OriginalServings  *int   `json:"original_serving_size"`
	DifficultyRating  *int   `json:"difficulty_rating"`
	FocusedDiet       string `json:"focused_diet"`
	EstimatedCalories *int   `json:"estimated_calories"`
}
